### PR TITLE
Adding Code tab for paginator component and some fixes in button and alert

### LINKED ISSUE #1035: Add Code tab to Paginator page

### PR DESCRIPTION
**Pull request by jsuarezgonz**
Closes #1035

### CODE REVIEW

File: website/screens/components/alert/code/examples/basicUsage.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
+import { DxcAlert, DxcInset, DxcStack } from "@dxc-technology/halstack-react";
+
+const code = `() => {
```
Comment (raquelarrojo) [inline website/screens/components/alert/code/examples/basicUsage.ts:3]: Remove DxcStack unnecessary import.

**Review by raquelarrojo — CHANGES_REQUESTED** [review]

File: website/screens/components/alert/code/examples/basicUsage.ts (hunk 1 above)
Comment (jsuarezgonz) [reply website/screens/components/alert/code/examples/basicUsage.ts:3]: Done.

**Review by raquelarrojo — APPROVED** [review]
