### PR TITLE
Fixing typing for the whole Select component

### LINKED ISSUE #1555: Remove ts-nocheck from Select
Remove `ts-nocheck` from Select.

### PR DESCRIPTION
**Pull request by Mil4n0r**
**Checklist**

- [x] Build process is done without errors. All tests pass in the `/lib` directory.
- [x] Self-reviewed the code before submitting.
- [x] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [x] Added/updated tests as needed.

**Description**
Removed ts-nocheck and fixed the problems related to it. Also typed all the methods and variables.

**Additional context**
A few small changes to logic were made in order to allow a better readibility and, overall, cleaner code. Also removed redundant types (SingleSelect and MultipleSelect could be merged into one type).

**Closes #1555**

### CODE REVIEW

File: lib/src/select/types.ts [hunk 1]
```diff
@@ -103,43 +103,14 @@ type CommonProps = {
...
-type MultipleSelect = CommonProps & {
+
+type Props = CommonProps & {
   /**
    * If true, the select component will support multiple selected options.
    * In that case, value will be an array of strings with each selected
    * option value.
    */
-  multiple: true;
+  multiple?: boolean;
```
Comment (GomezIvann) [inline lib/src/select/types.ts:113]: We should stick to the previous implementation with `SingleSelect` and `MultipleSelect` types. The point of how it was done was to guide the user through the construction of a Select using the types. For example, if `multiple` is true, the `defaultValue` should be an array of strings.

The solution should only be in the Select.tsx files, not in the current types.

**Review by GomezIvann — CHANGES_REQUESTED** [review]

File: lib/src/select/types.ts (hunk 1 above)
Comment (Mil4n0r) [reply lib/src/select/types.ts:113]: The problem is that, using those types, for some reason both the onChange and the onBlur callback seem to be inferred as the following: 

```
(val: {
    value: string;
    error?: string;
} & {
    value: string[];
    error?: string;
}) => void
```
Instead of the expected:
```
((val: {
    value: string;
    error?: string;
}) => void) | ((val: {
    value: string[];
    error?: string;
}) => void)
```

I have tried the approach recommended here: [Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html) among others recommended in forums with no success for this case.

Comment (Mil4n0r) [reply lib/src/select/types.ts]: We have decided that the best and easiest approach would be to use type assertion. [More info here](https://stackoverflow.com/questions/76188330/typescript-union-type-of-functions-weirdly-becomes-an-intersection-type-of-the-a)

File: lib/src/select/Select.tsx [hunk 2]
```diff
@@ -151,8 +147,8 @@ const DxcSelect = React.forwardRef<RefType, SelectPropsType>(
     const [visualFocusIndex, changeVisualFocusIndex] = useState(-1);
     const [isOpen, changeIsOpen] = useState(false);
 
-    const selectRef = useRef(null);
-    const selectSearchInputRef = useRef(null);
+    const selectRef = useRef<HTMLInputElement | null>(null);
```
Comment (GomezIvann) [inline lib/src/select/Select.tsx:150]: The select ref is on a div element (<Select> styled-component). We should type this one as an `HTMLDivElement`.

Comment (GomezIvann) [reply lib/src/select/Select.tsx:150]: This affects the `useWidth` parameter, it should also be an `HTMLDivElement` element.

File: lib/src/select/Select.tsx [hunk 3]
```diff
@@ -292,27 +288,27 @@ const DxcSelect = React.forwardRef<RefType, SelectPropsType>(
...
 
-    const handleSearchIOnChange = (event) => {
+    const handleSearchIOnChange = (event: React.ChangeEvent<HTMLInputElement>) => {
       setSearchValue(event.target.value);
       changeVisualFocusIndex(-1);
       openOptions();
     };
 
-    const handleClearOptionsActionOnClick = (event) => {
+    const handleClearOptionsActionOnClick = (event: React.MouseEvent) => {
```
Comment (GomezIvann) [inline lib/src/select/Select.tsx:297]: I think we should type the MouseEvent like this: `React.MouseEvent<HTMLButtonElement>`.

File: lib/src/select/Select.tsx [hunk 4]
```diff
@@ -292,27 +288,27 @@ const DxcSelect = React.forwardRef<RefType, SelectPropsType>(
...
       value ?? setInnerValue([]);
       !optional
-        ? onChange?.({ value: [], error: translatedLabels.formFields.requiredValueErrorMessage })
-        : onChange?.({ value: [] });
+        ? onChange?.({ value: [] as string & string[], error: translatedLabels.formFields.requiredValueErrorMessage })
+        : onChange?.({ value: [] as string & string[]});
     };
 
-    const handleClearSearchActionOnClick = (event) => {
+    const handleClearSearchActionOnClick = (event: React.MouseEvent) => {
```
Comment (GomezIvann) [inline lib/src/select/Select.tsx:305]: Same as above.

**Review by GomezIvann — CHANGES_REQUESTED** [review]

**Comment by GomezIvann** [comment]
One last comment, the code is unformatted. Can you please install the code formatter we use in Halstack in your Visual Studio Code IDE?

Name: Prettier - Code formatter
Id: esbenp.prettier-vscode
Description: Code formatter using prettier
Version: 10.1.0
Publisher: Prettier
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

File: lib/src/select/Select.tsx [hunk 5]
```diff
@@ -1,31 +1,27 @@
...
 import Listbox from "./Listbox";
 import * as Popover from "@radix-ui/react-popover";
 
-const groupsHaveOptions = (innerOptions) =>
-  innerOptions[0].hasOwnProperty("options")
-    ? innerOptions[0].options
-      ? innerOptions.some((groupOption) => groupOption.options.length > 0)
-      : false
-    : true;
+const isOption = (option: Option | OptionGroup): option is OptionGroup => 'options' in option;
```
[the remark this answers is not in the document]
Comment (Mil4n0r) [reply lib/src/select/Select.tsx]: Your proposal looks good to me!

**Comment by Mil4n0r** [comment]
Thanks for the detailed review Iván! I just added the requested changes 😄

**Review by GomezIvann — APPROVED** [review]

**Comment by GomezIvann** [comment]
Great job Enrique, this was a tough one!
