### PR TITLE
Fixed underline issue within `Tabs`

### LINKED ISSUE #2110: The bottom border of the active tab disappears under certain conditions
**Describe the bug**
The bottom border of the active tab disappears under certain conditions while using the new "Controlled" Tabs.

**To reproduce**
Follow these steps:

1. Open the following link: https://developer.dxc.com/halstack/14/components/tabs/.
2. Scroll down to the "Controlled" Tabs example.
3. Select different tabs and then click outside the tabs component.
4. Notice that the bottom border of the active tab disappears.

**Expected behaviour**
The bottom border should remain visible on the active tab while using the "Controlled" Tabs.

### PR DESCRIPTION
**Pull request by Mil4n0r**
**Checklist**

- [x] Build process is done without errors. All tests pass in the `/lib` directory.
- [x] Self-reviewed the code before submitting.
- [x] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [x] Added/updated tests as needed.

**Description**
Under certain interactions, the underline for the active item would move down until not being shown at all.

**Additional context**
It has been happening since `DxcTabs` API was refactorized to use compound component. A change in the dependency array to calculate the width and height was causing this problem.

**Closes #2110**

### CODE REVIEW

File: packages/lib/src/tabs/Tabs.tsx [hunk 1]
```diff
@@ -93,7 +93,7 @@ const DxcTabs = ({
       setTotalTabsWidth(refTabList.current.firstElementChild?.offsetWidth);
       setMinHeightTabs(refTabList?.current?.offsetHeight + 1);
     }
-  }, [childrenArray]);
+  }, [refTabList]);
```
Comment (GomezIvann) [inline packages/lib/src/tabs/Tabs.tsx:96]: Refs do not go inside the dependency array.

**Review by GomezIvann — CHANGES_REQUESTED** [review]

File: packages/lib/src/tabs/Tabs.tsx (hunk 1 above)
Comment (Mil4n0r) [reply packages/lib/src/tabs/Tabs.tsx:96]: That's why it was initially changed, the problem here is that in case the tab list is updated, the total width needs to be updated.

Comment (Mil4n0r) [reply packages/lib/src/tabs/Tabs.tsx:96]: Totally right. I'm leaving it as a Draft until I fix this.

**Review by GomezIvann — APPROVED** [review]
