### PR TITLE
Fix different spec image caption in website

### LINKED ISSUE #1491: Different spec image title in each component
**Describe the bug**
In the spec section, we have a different spec image title for each component.

**Expected behaviour**
We should have the same title for the same image. 
I would suggest: ` *Component name* design specifications`
Example: `Button design specifications`

**Screenshots**
image
image
image

**Add labels**
Website

### PR DESCRIPTION
**Pull request by raquelarrojo**
**Checklist**
_(Check off all the items before submitting)_

- [x] Build process is done without errors. All tests pass in the `/lib` directory.
- [x] Self-reviewed the code before submitting.
- [x] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [ ] Added/updated tests as needed.

**Description**

- Specs images captions are different in all components. Now this is fixed so that all captions follow the same structure.
- Fix several inconsistencies in usage pages.

**Closes #1491**

### CODE REVIEW

File: website/screens/components/accordion/usage/AccordionUsagePage.tsx [hunk 1]
```diff
@@ -96,21 +93,21 @@ const sections = [
...
-            <DxcParagraph>
-              <em>
-                <strong>Right</strong>. Don’t place caret icon on the left.
-              </em>
-            </DxcParagraph>
+            <Figure
+              caption={
+                <>
+                  <DxcParagraph>
+                    <strong>Left</strong>. Place chevron icon at the end of the
```
Comment (jsuarezgonz) [inline website/screens/components/accordion/usage/AccordionUsagePage.tsx:100]: `<em>` tag is missing.

**Review by jsuarezgonz — CHANGES_REQUESTED** [review]

File: website/screens/components/accordion/usage/AccordionUsagePage.tsx (hunk 1 above)
Comment (raquelarrojo) [reply website/screens/components/accordion/usage/AccordionUsagePage.tsx:100]: The rest of <em> are removed.

**Review by jsuarezgonz — APPROVED** [review]
