### PR TITLE
File input inside a form improvements

### LINKED ISSUE #1492: File Input bugs
- The description of the `callbackFile` prop does not specify at any point that it is going to be called whenever a file is added and also **deleted** (any time the inner value is modified, basically). We need to be more precise with this one.

image

- The internal hidden input value (value in forms) of the File Input does not work as expected. It only stores the first value(s) uploaded. If the user adds more files or deletes some of added ones, the internal input does not take it into account and submits the first stored values.

[screen-capture.webm](https://user-images.githubusercontent.com/44321109/220626269-393a4980-48d2-4cc6-910b-460821237c45.webm)

### PR DESCRIPTION
**Pull request by raquelarrojo**
**Checklist**
_(Check off all the items before submitting)_
- [x] Build process is done without errors and all tests pass in `/lib` directory.
- [x] Self-reviewed the code prior to submitting.
- [x] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [x] Added/updated tests as needed.

**Purpose**
Improve file input's documentation and behavior.

**Description**
- Improved `callbackFile` description in props table.
- Removed `name` from the input file to avoid that inconsistent data is received in submit inside a form.
- Added `type="button"` to file item's delete button, since by default button type is `submit`. This would cause a problem when the file input is inside a form.
- Changes `basicUsage` example to print `files` stateful variable instead of input file' `files`. Input file is uncontrolled and files are read only, so they do not contain files updated.
- Added file input inside a form example.
- Remove file input inside a form test, since we are not controlling what is arriving in submit event.

**Closes #1492**

### CODE REVIEW

File: lib/src/file-input/FileInput.tsx [hunk 1]
```diff
@@ -179,7 +179,6 @@ const DxcFileInput = React.forwardRef<RefType, FileInputPropsType>(
                 accept={accept}
                 multiple={multiple}
                 onChange={selectFiles}
-                name={name}
                 disabled={disabled}
                 readOnly
                 aria-hidden="true"
```
Comment (GomezIvann) [inline lib/src/file-input/FileInput.tsx:184]: One comment here. I recently discovered that aria-hidden is not necessary when an element is hidden using `display: none;`

image


https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden

Can you please remove it from this hidden input?

File: lib/src/file-input/FileInput.tsx [hunk 2]
```diff
@@ -223,7 +222,6 @@ const DxcFileInput = React.forwardRef<RefType, FileInputPropsType>(
...
```
Comment (GomezIvann) [inline lib/src/file-input/FileInput.tsx:227]: Same here.

File: website/screens/components/file-input/code/examples/formFileInput.ts [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+  return (
+    <form onSubmit={handleSubmit}>
+      <DxcInset space="2rem">
+        <DxcFlex direction="column" gap="2rem">
+          <DxcFileInput
+            label="Select your files"
+            value={files}
+            callbackFile={callbackFile}
+          />
+          <input type="submit" value="Submit" />
```
Comment (GomezIvann) [inline website/screens/components/file-input/code/examples/formFileInput.ts:30]: I think we should use our implementation of a submit button instead of the browser's one: `<DxcButton type="submit" label="Submit" />`.

Comment (GomezIvann) [reply website/screens/components/file-input/code/examples/formFileInput.ts:30]: I know it looks very similar to the first example, but I think they will understand the slight but important difference.

File: lib/src/file-input/FileInput.tsx (hunk 1 above)
Comment (raquelarrojo) [reply lib/src/file-input/FileInput.tsx]: Totally agree!
Done.

File: lib/src/file-input/FileInput.tsx (hunk 2 above)
Comment (raquelarrojo) [reply lib/src/file-input/FileInput.tsx]: Done!

File: website/screens/components/file-input/code/examples/formFileInput.ts (hunk 3 above)
Comment (raquelarrojo) [reply website/screens/components/file-input/code/examples/formFileInput.ts]: Agree! Done.

**Review by GomezIvann — APPROVED** [review]
