### PR TITLE
Fix `DxcLink` border radius

### LINKED ISSUE #1719: Update Link component `border-radius`
For consistency purposes, the  `border-radius` of the Link component is `2px` and we want to update it to `4px`. This is its value in most of our components. So, the tasks here are:

- [ ] Update the component implementation.
- [ ] Update the specifications, both images and possible token values.

### PR DESCRIPTION
**Pull request by Mil4n0r**
**Checklist**
_(Check off all the items before submitting)_

- [ ] Build process is done without errors. All tests pass in the `/lib` directory.
- [ ] Self-reviewed the code before submitting.
- [ ] Meets accessibility standards.
- [ ] Added/updated documentation to `/website` as needed.
- [ ] Added/updated tests as needed.

**Description**
For consistency purposes, the border-radius of the Link component is 2px and we want to update it to 4px. This is its value in most of our components. 

**Additional context**
Even though it was listed as 2px, the images used were using `border-radius: 4px` internally. That is why it is only required to change the first image in the Specifications tab.

**Closes #1719**

### CODE REVIEW

File: packages/lib/src/link/Link.tsx [hunk 1]
```diff
@@ -107,7 +107,7 @@ const StyledLink = styled.div<{
        cursor: pointer;`}
   }
   &:focus {
-    border-radius: 2px;
+    border-radius: 4px;
```
Comment (GomezIvann) [inline packages/lib/src/link/Link.tsx:110]: If you hover the link while being focused, the `border-bottom` bends over the edges, which was noticeable until now, since the `border-radius` has been increased, we need to figure out another way to implement this.

**Review by GomezIvann — CHANGES_REQUESTED** [review]

File: packages/lib/src/link/Link.tsx (hunk 1 above)
Comment (Mil4n0r) [reply packages/lib/src/link/Link.tsx:110]: I'll contact design to determine what the best solution for this is 
image

Comment (Mil4n0r) [reply packages/lib/src/link/Link.tsx]: After talking to Irene, adding a 2px padding and slightly changing how the styles are applied seems to be appropiate.

**Comment by Mil4n0r** [comment]
All images have been updated.

File: packages/lib/src/link/Link.tsx [hunk 2]
```diff
@@ -107,8 +107,19 @@ const StyledLink = styled.div<{
...
+      margin: -2px;
+      position: absolute;
+      top: 0;
+      right: 0;
+      bottom: 0;
+      left: 0;
+      border-radius: 4px;
+      outline: 2px solid ${(props) => props.theme.focusColor};
+      pointer-events: none;
+    }
```
Comment (Mil4n0r) [inline packages/lib/src/link/Link.tsx:122]: This is not the cleanest workaround but I haven't found anything else that worked as expected. Feel free to suggest a different solution.

File: packages/lib/src/link/Link.tsx [hunk 3]
```diff
@@ -78,44 +78,37 @@ const StyledLink = styled.div<{
...
+      ${(props) => `color: ${props.theme.visitedFontColor};
+                    border-bottom-color: ${props.theme.visitedUnderlineColor};`}
     }
   }
-  &:hover {
-    ${(props) =>
-      `color: ${props.theme.hoverFontColor};
-       border-bottom-color: ${props.theme.hoverUnderlineColor};
-       cursor: pointer;`}
+  &:active {
```
Comment (GomezIvann) [inline packages/lib/src/link/Link.tsx:100]: We can move the `:active` selector to the `LinkContainer` styled component and remove the `& > span` selector.

**Review by GomezIvann — COMMENTED** [review]
One comment, comparing the component with the designs and the specs images I still think the component is too tall. Maybe we need to adjust this by updating the `line-height`, what do you think? Maybe we need Lara or Irene's help.

image

File: packages/lib/src/link/Link.tsx (hunk 3 above)
Comment (Mil4n0r) [reply packages/lib/src/link/Link.tsx:100]: AFAIK, :active selector only works for <a> or <button> (the same as :visited), so I don't think it is suitable for this case.

Comment (GomezIvann) [reply packages/lib/src/link/Link.tsx:100]: Did you try? I tested it and it worked fine.

**Comment by Mil4n0r** [comment]
> One comment, comparing the component with the designs and the specs images I still think the component is too tall. Maybe we need to adjust this by updating the `line-height`, what do you think? Maybe we need Lara or Irene's help.
> 
> image

I missed that, but I agree with you that it is too tall. Using 100% line-height for the anchor seems to look just like in the images.

File: apps/website/screens/components/link/specs/images/link_states.png
Comment (GomezIvann) [inline apps/website/screens/components/link/specs/images/link_states.png:1]: The underline of the hover should fulfil the whole width of the component.

**Review by GomezIvann — CHANGES_REQUESTED** [review]

**Review by GomezIvann — APPROVED** [review]
