### PR TITLE
Chip spacing fix

### LINKED ISSUE #1608: Chip component has an extra right space
**Describe the bug**
There are two things to address:

1. Remove extra space at the right side of the component, which is the look of the component.
2. Fix the stories of the component. They aren't displaying any sort of text ellipsis, although the examples say the opposite.

**Expected behaviour**

1. Not having an unnecessary space at the right part of the container.
3. Have stories with actual text ellipsis.

**Screenshots**

image
image

### PR DESCRIPTION
**Pull request by GomezIvann**
**Checklist**
_(Check off all the items before submitting)_
- [x] Build process is done without errors and all tests pass in the `/lib` directory.
- [x] Self-reviewed the code before submitting.
- [x] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [x] Added/updated tests as needed.

**Description**
Summary:
- Fixes a spacing issue in the container of the Chip component.
- Some accessibility improvements to the component and small fixes to how interactive icons look.
- Code page updated with better explanations and examples.

**Screenshots**

image

**Closes #1608**

### CODE REVIEW

File: website/screens/components/chip/code/ChipCodePage.tsx [hunk 1]
```diff
@@ -29,22 +29,36 @@ const sections = [
           <tr>
             <td>prefixIcon: node | string</td>
             <td></td>
-            <td>Element used as icon to be placed before the chip label.</td>
+            <td>
+              Element used as icon, placed before the chip label. Note that if
+              the passed value is an URL (string), the component's color styling
+              tokens will not be applied to the image.
```
Comment (Jialecl) [inline website/screens/components/chip/code/ChipCodePage.tsx:35]: Not any SVG will get color styling applied, they need to inherit them from the chip tokens.

Comment (GomezIvann) [reply website/screens/components/chip/code/ChipCodePage.tsx:35]: I'm not saying that only using SVG would make it work, but I can explain it better.

**Review by Jialecl — APPROVED** [review]
